version: '3'

services:
  postgres:
    image: postgres
    container_name: todo_pg
    environment:
      - POSTGRES_USER=todo_pg_user
      - POSTGRES_PASSWORD=todo_pg_pass
      - POSTGRES_DB=todo_pg_db
    ports:
      - 5432:5432
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: todo_redis
    ports:
      - 6379:6379
    volumes:
      - todo_redis_data:/var/lib/redis

volumes:
  todo_pg_data:
  todo_redis_data:
