version: '3'
services:
  postgres:
    image: postgres:13.2
    container_name: todo_pg
    environment:
      - POSTGRES_USER=todo_pg_user
      - POSTGRES_PASSWORD=todo_pg_pass
      - POSTGRES_DB=todo_pg_db
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: todo_redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
volumes:
  pg:
  redis:
